I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 56, in script
    b "Komm, gehen wir zum Juwelier! Ich möchte dir etwas kaufen."
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 56, in script
    b "Komm, gehen wir zum Juwelier! Ich möchte dir etwas kaufen."
  File "/Users/StefanSafradin/Downloads/renpy-6.18.3-sdk/renpy/ast.py", line 573, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/StefanSafradin/Downloads/renpy-6.18.3-sdk/renpy/ast.py", line 491, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'b' is not defined.

Darwin-14.0.0-x86_64-i386-64bit
Ren'Py 6.18.3.761
test 0.0
